export const questions = [
  {
    answers: null,
    correctAnswer: '',
    id: 1,
    question:
      'Explain the concept of polymorphism in object-oriented programming.',
    questionType: 'theoretical',
  },
  {
    answers: null,
    correctAnswer: 'false',
    id: 2,
    question: 'JavaScript is a statically typed language.',
    questionType: 'trueOrFalse',
  },
  {
    answers: 'React,Vue,Angular,Svelte',
    correctAnswer: 'React',
    id: 3,
    question: 'Which of the following is a JavaScript framework?',
    questionType: 'multipleChoice',
  },
  {
    answers: null,
    correctAnswer: '',
    id: 4,
    question: 'Describe the main differences between HTTP and HTTPS.',
    questionType: 'theoretical',
  },
  {
    answers: null,
    correctAnswer: 'true',
    id: 5,
    question: 'CSS stands for Cascading Style Sheets.',
    questionType: 'trueOrFalse',
  },
  {
    answers: 'MongoDB,MySQL,PostgreSQL,SQLite',
    correctAnswer: 'MongoDB',
    id: 6,
    question: 'Which of the following is a non-relational database?',
    questionType: 'multipleChoice',
  },
  {
    answers: null,
    correctAnswer: '',
    id: 7,
    question: 'What are the key features of the Agile methodology?',
    questionType: 'theoretical',
  },
  {
    answers: null,
    correctAnswer: 'true',
    id: 8,
    question: 'HTML is used to structure content on the web.',
    questionType: 'trueOrFalse',
  },
  {
    answers: 'Django,Laravel,Spring,Angular',
    correctAnswer: 'Angular',
    id: 9,
    question: 'Which of the following is a front-end framework?',
    questionType: 'multipleChoice',
  },
  {
    answers: null,
    correctAnswer: '',
    id: 10,
    question:
      'Explain the importance of version control in software development.',
    questionType: 'theoretical',
  },
  {
    answers: null,
    correctAnswer: 'false',
    id: 11,
    question: 'Python is a compiled language.',
    questionType: 'trueOrFalse',
  },
  {
    answers: 'Python,JavaScript,HTML,CSS',
    correctAnswer: 'Python',
    id: 12,
    question: 'Which of the following is a back-end programming language?',
    questionType: 'multipleChoice',
  },
  {
    answers: null,
    correctAnswer: '',
    id: 13,
    question: 'Discuss the benefits of using a microservices architecture.',
    questionType: 'theoretical',
  },
  {
    answers: null,
    correctAnswer: 'true',
    id: 14,
    question: 'SQL is used to interact with databases.',
    questionType: 'trueOrFalse',
  },
  {
    answers: 'AWS,Heroku,GitHub,Netlify',
    correctAnswer: 'AWS',
    id: 15,
    question: 'Which of the following is a cloud service provider?',
    questionType: 'multipleChoice',
  },
  {
    answers: null,
    correctAnswer: '',
    id: 16,
    question: 'What are the advantages of using TypeScript over JavaScript?',
    questionType: 'theoretical',
  },
  {
    answers: null,
    correctAnswer: 'true',
    id: 17,
    question: 'Docker is used for containerization.',
    questionType: 'trueOrFalse',
  },
  {
    answers: 'Git,Node.js,Docker,Kubernetes',
    correctAnswer: 'Git',
    id: 18,
    question: 'Which of the following is a version control system?',
    questionType: 'multipleChoice',
  },
  {
    answers: null,
    correctAnswer: '',
    id: 19,
    question: 'Explain the role of a load balancer in a web application.',
    questionType: 'theoretical',
  },
  {
    answers: null,
    correctAnswer: 'true',
    id: 20,
    question: 'RESTful APIs use JSON as the standard data format.',
    questionType: 'trueOrFalse',
  },
];
