export default [
  {
    category: 'Accessories',
    code: 'f230fh0g3',
    description: 'Product Description',
    id: '1000',
    image: 'bamboo-watch.jpg',
    inventoryStatus: 'INSTOCK',
    name: 'Bamboo Watch',
    // price: 65,
    quantity: 24,
    rating: 5,
  },
  {
    category: 'Accessories',
    code: 'nvklal433',
    description: 'Product Description',
    id: '1001',
    image: 'black-watch.jpg',
    inventoryStatus: 'INSTOCK',
    name: 'Black Watch',
    price: 72,
    quantity: 61,
    rating: 4,
  },
  {
    category: 'Fitness',
    code: 'zz21cz3c1',
    description: 'Product Description',
    id: '1002',
    image: 'blue-band.jpg',
    inventoryStatus: 'LOWSTOCK',
    name: 'Blue Band',
    price: 79,
    quantity: 2,
    rating: 3,
  },
  {
    category: 'Clothing',
    code: '244wgerg2',
    description: 'Product Description',
    id: '1003',
    image: 'blue-t-shirt.jpg',
    inventoryStatus: 'INSTOCK',
    name: 'Blue T-Shirt',
    price: 29,
    quantity: 25,
    rating: 5,
  },
  {
    category: 'Accessories',
    code: 'h456wer53',
    description: 'Product Description',
    id: '1004',
    image: 'bracelet.jpg',
    inventoryStatus: 'INSTOCK',
    name: 'Bracelet',
    price: 15,
    quantity: 73,
    rating: 4,
  },
  {
    category: 'Accessories',
    code: 'av2231fwg',
    description: 'Product Description',
    id: '1005',
    image: 'brown-purse.jpg',
    inventoryStatus: 'OUTOFSTOCK',
    name: 'Brown Purse',
    price: 120,
    quantity: 0,
    rating: 4,
  },
  {
    category: 'Accessories',
    code: 'bib36pfvm',
    description: 'Product Description',
    id: '1006',
    image: 'chakra-bracelet.jpg',
    inventoryStatus: 'LOWSTOCK',
    name: 'Chakra Bracelet',
    price: 32,
    quantity: 5,
    rating: 3,
  },
  {
    category: 'Accessories',
    code: 'mbvjkgip5',
    description: 'Product Description',
    id: '1007',
    image: 'galaxy-earrings.jpg',
    inventoryStatus: 'INSTOCK',
    name: 'Galaxy Earrings',
    price: 34,
    quantity: 23,
    rating: 5,
  },
  {
    category: 'Electronics',
    code: 'vbb124btr',
    description: 'Product Description',
    id: '1008',
    image: 'game-controller.jpg',
    inventoryStatus: 'LOWSTOCK',
    name: 'Game Controller',
    price: 99,
    quantity: 2,
    rating: 4,
  },
  {
    category: 'Electronics',
    code: 'cm230f032',
    description: 'Product Description',
    id: '1009',
    image: 'gaming-set.jpg',
    inventoryStatus: 'INSTOCK',
    name: 'Gaming Set',
    price: 299,
    quantity: 63,
    rating: 3,
  },
  {
    category: 'Accessories',
    code: 'plb34234v',
    description: 'Product Description',
    id: '1010',
    image: 'gold-phone-case.jpg',
    inventoryStatus: 'OUTOFSTOCK',
    name: 'Gold Phone Case',
    price: 24,
    quantity: 0,
    rating: 4,
  },
  {
    category: 'Electronics',
    code: '4920nnc2d',
    description: 'Product Description',
    id: '1011',
    image: 'green-earbuds.jpg',
    inventoryStatus: 'INSTOCK',
    name: 'Green Earbuds',
    price: 89,
    quantity: 23,
    rating: 4,
  },
  {
    category: 'Clothing',
    code: '250vm23cc',
    description: 'Product Description',
    id: '1012',
    image: 'green-t-shirt.jpg',
    inventoryStatus: 'INSTOCK',
    name: 'Green T-Shirt',
    price: 49,
    quantity: 74,
    rating: 5,
  },
  {
    category: 'Clothing',
    code: 'fldsmn31b',
    description: 'Product Description',
    id: '1013',
    image: 'grey-t-shirt.jpg',
    inventoryStatus: 'OUTOFSTOCK',
    name: 'Grey T-Shirt',
    price: 48,
    quantity: 0,
    rating: 3,
  },
  {
    category: 'Electronics',
    code: 'waas1x2as',
    description: 'Product Description',
    id: '1014',
    image: 'headphones.jpg',
    inventoryStatus: 'LOWSTOCK',
    name: 'Headphones',
    price: 175,
    quantity: 8,
    rating: 5,
  },
  {
    category: 'Clothing',
    code: 'vb34btbg5',
    description: 'Product Description',
    id: '1015',
    image: 'light-green-t-shirt.jpg',
    inventoryStatus: 'INSTOCK',
    name: 'Light Green T-Shirt',
    price: 49,
    quantity: 34,
    rating: 4,
  },
  {
    category: 'Fitness',
    code: 'k8l6j58jl',
    description: 'Product Description',
    id: '1016',
    image: 'lime-band.jpg',
    inventoryStatus: 'INSTOCK',
    name: 'Lime Band',
    price: 79,
    quantity: 12,
    rating: 3,
  },
  {
    category: 'Clothing',
    code: 'v435nn85n',
    description: 'Product Description',
    id: '1017',
    image: 'mini-speakers.jpg',
    inventoryStatus: 'INSTOCK',
    name: 'Mini Speakers',
    price: 85,
    quantity: 42,
    rating: 4,
  },
  {
    category: 'Accessories',
    code: '09zx9c0zc',
    description: 'Product Description',
    id: '1018',
    image: 'painted-phone-case.jpg',
    inventoryStatus: 'INSTOCK',
    name: 'Painted Phone Case',
    price: 56,
    quantity: 41,
    rating: 5,
  },
  {
    category: 'Fitness',
    code: 'mnb5mb2m5',
    description: 'Product Description',
    id: '1019',
    image: 'pink-band.jpg',
    inventoryStatus: 'INSTOCK',
    name: 'Pink Band',
    price: 79,
    quantity: 63,
    rating: 4,
  },
  {
    category: 'Accessories',
    code: 'r23fwf2w3',
    description: 'Product Description',
    id: '1020',
    image: 'pink-purse.jpg',
    inventoryStatus: 'OUTOFSTOCK',
    name: 'Pink Purse',
    price: 110,
    quantity: 0,
    rating: 4,
  },
  {
    category: 'Fitness',
    code: 'pxpzczo23',
    description: 'Product Description',
    id: '1021',
    image: 'purple-band.jpg',
    inventoryStatus: 'LOWSTOCK',
    name: 'Purple Band',
    price: 79,
    quantity: 6,
    rating: 3,
  },
  {
    category: 'Accessories',
    code: '2c42cb5cb',
    description: 'Product Description',
    id: '1022',
    image: 'purple-gemstone-necklace.jpg',
    inventoryStatus: 'INSTOCK',
    name: 'Purple Gemstone Necklace',
    price: 45,
    quantity: 62,
    rating: 4,
  },
  {
    category: 'Clothing',
    code: '5k43kkk23',
    description: 'Product Description',
    id: '1023',
    image: 'purple-t-shirt.jpg',
    inventoryStatus: 'LOWSTOCK',
    name: 'Purple T-Shirt',
    price: 49,
    quantity: 2,
    rating: 5,
  },
  {
    category: 'Clothing',
    code: 'lm2tny2k4',
    description: 'Product Description',
    id: '1024',
    image: 'shoes.jpg',
    inventoryStatus: 'INSTOCK',
    name: 'Shoes',
    price: 64,
    quantity: 0,
    rating: 4,
  },
  {
    category: 'Clothing',
    code: 'nbm5mv45n',
    description: 'Product Description',
    id: '1025',
    image: 'sneakers.jpg',
    inventoryStatus: 'INSTOCK',
    name: 'Sneakers',
    price: 78,
    quantity: 52,
    rating: 4,
  },
  {
    category: 'Clothing',
    code: 'zx23zc42c',
    description: 'Product Description',
    id: '1026',
    image: 'teal-t-shirt.jpg',
    inventoryStatus: 'LOWSTOCK',
    name: 'Teal T-Shirt',
    price: 49,
    quantity: 3,
    rating: 3,
  },
  {
    category: 'Electronics',
    code: 'acvx872gc',
    description: 'Product Description',
    id: '1027',
    image: 'yellow-earbuds.jpg',
    inventoryStatus: 'INSTOCK',
    name: 'Yellow Earbuds',
    price: 89,
    quantity: 35,
    rating: 3,
  },
  {
    category: 'Fitness',
    code: 'tx125ck42',
    description: 'Product Description',
    id: '1028',
    image: 'yoga-mat.jpg',
    inventoryStatus: 'INSTOCK',
    name: 'Yoga Mat',
    price: 20,
    quantity: 15,
    rating: 5,
  },
  {
    category: 'Fitness',
    code: 'gwuby345v',
    description: 'Product Description',
    id: '1029',
    image: 'yoga-set.jpg',
    inventoryStatus: 'INSTOCK',
    name: 'Yoga Set',
    price: 20,
    quantity: 25,
    rating: 8,
  },
];
